server:
  port: 8888
spring:
  application:
    name: financial-control
  data:
    mongodb:
      database: gps-api
      host: localhost
      port: 27017
      auto-index-creation: false
  main:
    banner-mode: off
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level %logger{35} - %msg%n'
  level:
    root: INFO
    org.springframework.data: DEBUG
    org.springframework.cache: DEBUG
springdoc:
  cache:
    disabled: true
  swagger-ui:
    display-request-duration: true
  version: '@springdoc.version@'